package com.ebstrada.formreturn.manager.persistence.xstream;

import com.ebstrada.formreturn.manager.gef.font.CachedFont;
import com.ebstrada.formreturn.manager.gef.font.CachedFontFamily;
import com.ebstrada.formreturn.manager.gef.font.CachedFontGroup;
import com.ebstrada.formreturn.manager.gef.presentation.Fig;
import com.ebstrada.formreturn.manager.gef.presentation.FigBarcode;
import com.ebstrada.formreturn.manager.gef.presentation.FigBarcodeReader;
import com.ebstrada.formreturn.manager.gef.presentation.FigCheckbox;
import com.ebstrada.formreturn.manager.gef.presentation.FigCircle;
import com.ebstrada.formreturn.manager.gef.presentation.FigGroup;
import com.ebstrada.formreturn.manager.gef.presentation.FigImage;
import com.ebstrada.formreturn.manager.gef.presentation.FigLine;
import com.ebstrada.formreturn.manager.gef.presentation.FigRRect;
import com.ebstrada.formreturn.manager.gef.presentation.FigRect;
import com.ebstrada.formreturn.manager.gef.presentation.FigSegment;
import com.ebstrada.formreturn.manager.gef.presentation.FigText;
import com.ebstrada.formreturn.manager.gef.ui.DocumentAttributes;
import com.ebstrada.formreturn.manager.gef.ui.PageAttributes;
import com.ebstrada.formreturn.manager.gef.ui.SegmentContainer;
import com.ebstrada.formreturn.manager.logic.export.ExportOptions;
import com.ebstrada.formreturn.manager.logic.export.filter.ExcludeEmptyRecordsFilter;
import com.ebstrada.formreturn.manager.logic.export.filter.Filter;
import com.ebstrada.formreturn.manager.logic.export.image.Collation;
import com.ebstrada.formreturn.manager.logic.export.image.ImageExportPreferences;
import com.ebstrada.formreturn.manager.logic.export.image.Overlay;
import com.ebstrada.formreturn.manager.logic.export.stats.StatisticMap;
import com.ebstrada.formreturn.manager.logic.export.xml.XMLExportPreferences;
import com.ebstrada.formreturn.manager.logic.recognition.structure.PublicationRecognitionStructure;
import com.ebstrada.formreturn.manager.ui.editor.persistence.FieldnameDuplicatePresets;
import com.ebstrada.formreturn.manager.ui.editor.persistence.JARPlugin;
import com.ebstrada.formreturn.manager.ui.editor.persistence.MarkingRule;
import com.ebstrada.formreturn.manager.ui.editor.persistence.MarkAreaPresetStyle;
import com.ebstrada.formreturn.manager.ui.editor.persistence.MarkingProperties;
import com.ebstrada.formreturn.manager.ui.editor.persistence.Plugins;
import com.ebstrada.formreturn.manager.ui.editor.persistence.Templates;
import com.ebstrada.formreturn.manager.ui.editor.persistence.XSLTemplate;
import com.ebstrada.formreturn.manager.util.NoObfuscation;
import com.ebstrada.formreturn.manager.util.graph.SizeAttributes;
import com.ebstrada.formreturn.manager.util.preferences.persistence.ApplicationStatePreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.ClientDatabasePreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.FolderMonitorPreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.FormProcessorPreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.FormReturnPreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.PublicationPreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.ScannerPreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.SoftwareUpdatePreferences;
import com.ebstrada.formreturn.manager.util.preferences.persistence.CSVExportPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.CustomJobPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.DatabaseServerPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.ExportJobPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.ImageFolderMonitorJobPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.ServerPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.SourceDataFolderMonitorJobPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.TaskSchedulerPreferences;
import com.ebstrada.formreturn.server.preferences.persistence.VacuumJobPreferences;
import com.swingsane.preferences.model.ApplicationPreferences;
import com.swingsane.preferences.model.BooleanOption;
import com.swingsane.preferences.model.ButtonOption;
import com.swingsane.preferences.model.Constraints;
import com.swingsane.preferences.model.FixedOption;
import com.swingsane.preferences.model.GroupOption;
import com.swingsane.preferences.model.GroupOptions;
import com.swingsane.preferences.model.IntegerOption;
import com.swingsane.preferences.model.Login;
import com.swingsane.preferences.model.Option;
import com.swingsane.preferences.model.OptionsOrderValuePair;
import com.swingsane.preferences.model.SaneServiceIdentity;
import com.swingsane.preferences.model.Scanner;
import com.swingsane.preferences.model.ScannerOptions;
import com.swingsane.preferences.model.StringOption;
import com.thoughtworks.xstream.XStream;

public class Annotations implements NoObfuscation {

    public static void load(XStream xstream) {

        // swingsane preferences
        xstream.processAnnotations(ApplicationPreferences.class);
        xstream.processAnnotations(Login.class);
        xstream.processAnnotations(SaneServiceIdentity.class);
        xstream.processAnnotations(Scanner.class);
        xstream.processAnnotations(BooleanOption.class);
        xstream.processAnnotations(ButtonOption.class);
        xstream.processAnnotations(Constraints.class);
        xstream.processAnnotations(FixedOption.class);
        xstream.processAnnotations(GroupOption.class);
        xstream.processAnnotations(GroupOptions.class);
        xstream.processAnnotations(IntegerOption.class);
        xstream.processAnnotations(Option.class);
        xstream.processAnnotations(ScannerOptions.class);
        xstream.processAnnotations(StringOption.class);
        xstream.processAnnotations(OptionsOrderValuePair.class);


        // formreturn preferences
        xstream.processAnnotations(FormReturnPreferences.class);
        xstream.processAnnotations(ServerPreferences.class);
        xstream.processAnnotations(ApplicationStatePreferences.class);
        xstream.processAnnotations(PublicationPreferences.class);
        xstream.processAnnotations(ClientDatabasePreferences.class);
        xstream.processAnnotations(SoftwareUpdatePreferences.class);
        xstream.processAnnotations(DatabaseServerPreferences.class);
        xstream.processAnnotations(FormProcessorPreferences.class);
        xstream.processAnnotations(FolderMonitorPreferences.class);
        xstream.processAnnotations(ScannerPreferences.class);
        xstream.processAnnotations(CSVExportPreferences.class);
        xstream.processAnnotations(SizeAttributes.class);
        xstream.processAnnotations(Page.class);
        xstream.processAnnotations(Document.class);
        xstream.processAnnotations(Fig.class);
        xstream.processAnnotations(FigBarcode.class);
        xstream.processAnnotations(FigBarcodeReader.class);
        xstream.processAnnotations(FigCheckbox.class);
        xstream.processAnnotations(FigCircle.class);
        xstream.processAnnotations(FigGroup.class);
        xstream.processAnnotations(FigImage.class);
        xstream.processAnnotations(FigLine.class);
        xstream.processAnnotations(FigRect.class);
        xstream.processAnnotations(FigRRect.class);
        xstream.processAnnotations(FigSegment.class);
        xstream.processAnnotations(FigText.class);
        xstream.processAnnotations(DocumentAttributes.class);
        xstream.processAnnotations(PageAttributes.class);
        xstream.processAnnotations(SegmentContainer.class);
        xstream.processAnnotations(MarkAreaPresetStyle.class);
        xstream.processAnnotations(FieldnameDuplicatePresets.class);
        xstream.processAnnotations(PublicationRecognitionStructure.class);
        xstream.processAnnotations(Templates.class);
        xstream.processAnnotations(XSLTemplate.class);
        xstream.processAnnotations(Plugins.class);
        xstream.processAnnotations(JARPlugin.class);
        xstream.processAnnotations(MarkingProperties.class);
        xstream.processAnnotations(MarkingRule.class);
        xstream.processAnnotations(CachedFontGroup.class);
        xstream.processAnnotations(CachedFontFamily.class);
        xstream.processAnnotations(CachedFont.class);
        xstream.processAnnotations(TaskSchedulerPreferences.class);
        xstream.processAnnotations(SourceDataFolderMonitorJobPreferences.class);
        xstream.processAnnotations(ImageFolderMonitorJobPreferences.class);
        xstream.processAnnotations(VacuumJobPreferences.class);
        xstream.processAnnotations(CustomJobPreferences.class);
        xstream.processAnnotations(ImageExportPreferences.class);
        xstream.processAnnotations(StatisticMap.class);
        xstream.processAnnotations(Filter.class);
        xstream.processAnnotations(ExportJobPreferences.class);
        xstream.processAnnotations(Collation.class);
        xstream.processAnnotations(Overlay.class);
        xstream.processAnnotations(ExcludeEmptyRecordsFilter.class);
        xstream.processAnnotations(ExportOptions.class);
        xstream.processAnnotations(XMLExportPreferences.class);
    }

}
